// src/data/countries.ts

/**
 * Comprehensive list of countries with dial codes and phone number format examples
 */
export const countries = [
    { code: 'AF', name: 'Afghanistan', dialCode: '+93', placeholder: '70 123 4567', flag: 'emojione-flag-for-afghanistan' },
    { code: 'AL', name: 'Albania', dialCode: '+355', placeholder: '69 123 4567', flag: 'emojione-flag-for-albania' },
    { code: 'DZ', name: 'Algeria', dialCode: '+213', placeholder: '551 23 45 67', flag: 'emojione-flag-for-algeria' },
    { code: 'AS', name: 'American Samoa', dialCode: '+1684', placeholder: '733 1234', flag: 'emojione-flag-for-american-samoa' },
    { code: 'AD', name: 'Andorra', dialCode: '+376', placeholder: '312 345', flag: 'emojione-flag-for-andorra' },
    { code: 'AO', name: 'Angola', dialCode: '+244', placeholder: '923 123 456', flag: 'emojione-flag-for-angola' },
    { code: 'AI', name: 'Anguilla', dialCode: '+1264', placeholder: '235 1234', flag: 'emojione-flag-for-anguilla' },
    { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1268', placeholder: '464 1234', flag: 'emojione-flag-for-antigua-and-barbuda' },
    { code: 'AR', name: 'Argentina', dialCode: '+54', placeholder: '11 2345 6789', flag: 'emojione-flag-for-argentina' },
    { code: 'AM', name: 'Armenia', dialCode: '+374', placeholder: '77 123456', flag: 'emojione-flag-for-armenia' },
    { code: 'AW', name: 'Aruba', dialCode: '+297', placeholder: '560 1234', flag: 'emojione-flag-for-aruba' },
    { code: 'AU', name: 'Australia', dialCode: '+61', placeholder: '412 345 678', flag: 'emojione-flag-for-australia' },
    { code: 'AT', name: 'Austria', dialCode: '+43', placeholder: '664 123456', flag: 'emojione-flag-for-austria' },
    { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', placeholder: '40 123 45 67', flag: 'emojione-flag-for-azerbaijan' },
    { code: 'BS', name: 'Bahamas', dialCode: '+1242', placeholder: '359 1234', flag: 'emojione-flag-for-bahamas' },
    { code: 'BH', name: 'Bahrain', dialCode: '+973', placeholder: '3600 1234', flag: 'emojione-flag-for-bahrain' },
    { code: 'BD', name: 'Bangladesh', dialCode: '+880', placeholder: '1812 345678', flag: 'emojione-flag-for-bangladesh' },
    { code: 'BB', name: 'Barbados', dialCode: '+1246', placeholder: '250 1234', flag: 'emojione-flag-for-barbados' },
    { code: 'BY', name: 'Belarus', dialCode: '+375', placeholder: '29 491 1911', flag: 'emojione-flag-for-belarus' },
    { code: 'BE', name: 'Belgium', dialCode: '+32', placeholder: '470 12 34 56', flag: 'emojione-flag-for-belgium' },
    { code: 'BZ', name: 'Belize', dialCode: '+501', placeholder: '622 1234', flag: 'emojione-flag-for-belize' },
    { code: 'BJ', name: 'Benin', dialCode: '+229', placeholder: '90 01 12 34', flag: 'emojione-flag-for-benin' },
    { code: 'BM', name: 'Bermuda', dialCode: '+1441', placeholder: '370 1234', flag: 'emojione-flag-for-bermuda' },
    { code: 'BT', name: 'Bhutan', dialCode: '+975', placeholder: '17 12 34 56', flag: 'emojione-flag-for-bhutan' },
    { code: 'BO', name: 'Bolivia', dialCode: '+591', placeholder: '7123 4567', flag: 'emojione-flag-for-bolivia' },
    { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', placeholder: '61 123 456', flag: 'emojione-flag-for-bosnia-and-herzegovina' },
    { code: 'BW', name: 'Botswana', dialCode: '+267', placeholder: '71 123 456', flag: 'emojione-flag-for-botswana' },
    { code: 'BR', name: 'Brazil', dialCode: '+55', placeholder: '11 98765 4321', flag: 'emojione-flag-for-brazil' },
    { code: 'IO', name: 'British Indian Ocean Territory', dialCode: '+246', placeholder: '380 1234', flag: 'emojione-flag-for-british-indian-ocean-territory' },
    { code: 'VG', name: 'British Virgin Islands', dialCode: '+1284', placeholder: '300 1234', flag: 'emojione-flag-for-british-virgin-islands' },
    { code: 'BN', name: 'Brunei', dialCode: '+673', placeholder: '712 3456', flag: 'emojione-flag-for-brunei' },
    { code: 'BG', name: 'Bulgaria', dialCode: '+359', placeholder: '48 123 456', flag: 'emojione-flag-for-bulgaria' },
    { code: 'BF', name: 'Burkina Faso', dialCode: '+226', placeholder: '70 12 34 56', flag: 'emojione-flag-for-burkina-faso' },
    { code: 'BI', name: 'Burundi', dialCode: '+257', placeholder: '79 56 12 34', flag: 'emojione-flag-for-burundi' },
    { code: 'KH', name: 'Cambodia', dialCode: '+855', placeholder: '91 234 567', flag: 'emojione-flag-for-cambodia' },
    { code: 'CM', name: 'Cameroon', dialCode: '+237', placeholder: '6 71 23 45 67', flag: 'emojione-flag-for-cameroon' },
    { code: 'CA', name: 'Canada', dialCode: '+1', placeholder: '506 234 5678', flag: 'emojione-flag-for-canada' },
    { code: 'CV', name: 'Cape Verde', dialCode: '+238', placeholder: '991 1234', flag: 'emojione-flag-for-cape-verde' },
    { code: 'KY', name: 'Cayman Islands', dialCode: '+1345', placeholder: '321 1234', flag: 'emojione-flag-for-cayman-islands' },
    { code: 'CF', name: 'Central African Republic', dialCode: '+236', placeholder: '70 01 23 45', flag: 'emojione-flag-for-central-african-republic' },
    { code: 'TD', name: 'Chad', dialCode: '+235', placeholder: '63 01 23 45', flag: 'emojione-flag-for-chad' },
    { code: 'CL', name: 'Chile', dialCode: '+56', placeholder: '9 6123 4567', flag: 'emojione-flag-for-chile' },
    { code: 'CN', name: 'China', dialCode: '+86', placeholder: '131 2345 6789', flag: 'emojione-flag-for-china' },
    { code: 'CO', name: 'Colombia', dialCode: '+57', placeholder: '321 1234567', flag: 'emojione-flag-for-colombia' },
    { code: 'KM', name: 'Comoros', dialCode: '+269', placeholder: '321 23 45', flag: 'emojione-flag-for-comoros' },
    { code: 'CG', name: 'Congo', dialCode: '+242', placeholder: '06 123 4567', flag: 'emojione-flag-for-congo-brazzaville' },
    { code: 'CD', name: 'Congo, Democratic Republic', dialCode: '+243', placeholder: '991 234 567', flag: 'emojione-flag-for-congo-kinshasa' },
    { code: 'CK', name: 'Cook Islands', dialCode: '+682', placeholder: '71 234', flag: 'emojione-flag-for-cook-islands' },
    { code: 'CR', name: 'Costa Rica', dialCode: '+506', placeholder: '8312 3456', flag: 'emojione-flag-for-costa-rica' },
    { code: 'CI', name: 'Côte d\'Ivoire', dialCode: '+225', placeholder: '01 23 45 67 89', flag: 'emojione-flag-for-cote-divoire' },
    { code: 'HR', name: 'Croatia', dialCode: '+385', placeholder: '91 234 5678', flag: 'emojione-flag-for-croatia' },
    { code: 'CU', name: 'Cuba', dialCode: '+53', placeholder: '5 1234567', flag: 'emojione-flag-for-cuba' },
    { code: 'CW', name: 'Curaçao', dialCode: '+599', placeholder: '9 518 1234', flag: 'emojione-flag-for-curacao' },
    { code: 'CY', name: 'Cyprus', dialCode: '+357', placeholder: '96 123456', flag: 'emojione-flag-for-cyprus' },
    { code: 'CZ', name: 'Czech Republic', dialCode: '+420', placeholder: '601 123 456', flag: 'emojione-flag-for-czechia' },
    { code: 'DK', name: 'Denmark', dialCode: '+45', placeholder: '20 12 34 56', flag: 'emojione-flag-for-denmark' },
    { code: 'DJ', name: 'Djibouti', dialCode: '+253', placeholder: '77 83 10 01', flag: 'emojione-flag-for-djibouti' },
    { code: 'DM', name: 'Dominica', dialCode: '+1767', placeholder: '225 1234', flag: 'emojione-flag-for-dominica' },
    { code: 'DO', name: 'Dominican Republic', dialCode: '+1', placeholder: '809 234 5678', flag: 'emojione-flag-for-dominican-republic' },
    { code: 'EC', name: 'Ecuador', dialCode: '+593', placeholder: '99 123 4567', flag: 'emojione-flag-for-ecuador' },
    { code: 'EG', name: 'Egypt', dialCode: '+20', placeholder: '10 1234 5678', flag: 'emojione-flag-for-egypt' },
    { code: 'SV', name: 'El Salvador', dialCode: '+503', placeholder: '7012 3456', flag: 'emojione-flag-for-el-salvador' },
    { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', placeholder: '222 123 456', flag: 'emojione-flag-for-equatorial-guinea' },
    { code: 'ER', name: 'Eritrea', dialCode: '+291', placeholder: '7 123 456', flag: 'emojione-flag-for-eritrea' },
    { code: 'EE', name: 'Estonia', dialCode: '+372', placeholder: '5123 4567', flag: 'emojione-flag-for-estonia' },
    { code: 'ET', name: 'Ethiopia', dialCode: '+251', placeholder: '91 123 4567', flag: 'emojione-flag-for-ethiopia' },
    { code: 'FK', name: 'Falkland Islands', dialCode: '+500', placeholder: '51234', flag: 'emojione-flag-for-falkland-islands' },
    { code: 'FO', name: 'Faroe Islands', dialCode: '+298', placeholder: '211234', flag: 'emojione-flag-for-faroe-islands' },
    { code: 'FJ', name: 'Fiji', dialCode: '+679', placeholder: '701 2345', flag: 'emojione-flag-for-fiji' },
    { code: 'FI', name: 'Finland', dialCode: '+358', placeholder: '41 2345678', flag: 'emojione-flag-for-finland' },
    { code: 'FR', name: 'France', dialCode: '+33', placeholder: '6 12 34 56 78', flag: 'emojione-flag-for-france' },
    { code: 'GF', name: 'French Guiana', dialCode: '+594', placeholder: '694 20 12 34', flag: 'emojione-flag-for-french-guiana' },
    { code: 'PF', name: 'French Polynesia', dialCode: '+689', placeholder: '87 12 34 56', flag: 'emojione-flag-for-french-polynesia' },
    { code: 'GA', name: 'Gabon', dialCode: '+241', placeholder: '06 03 12 34', flag: 'emojione-flag-for-gabon' },
    { code: 'GM', name: 'Gambia', dialCode: '+220', placeholder: '301 2345', flag: 'emojione-flag-for-gambia' },
    { code: 'GE', name: 'Georgia', dialCode: '+995', placeholder: '555 12 34 56', flag: 'emojione-flag-for-georgia' },
    { code: 'DE', name: 'Germany', dialCode: '+49', placeholder: '171 1234567', flag: 'emojione-flag-for-germany' },
    { code: 'GH', name: 'Ghana', dialCode: '+233', placeholder: '24 123 4567', flag: 'emojione-flag-for-ghana' },
    { code: 'GI', name: 'Gibraltar', dialCode: '+350', placeholder: '57123456', flag: 'emojione-flag-for-gibraltar' },
    { code: 'GR', name: 'Greece', dialCode: '+30', placeholder: '691 234 5678', flag: 'emojione-flag-for-greece' },
    { code: 'GL', name: 'Greenland', dialCode: '+299', placeholder: '22 12 34', flag: 'emojione-flag-for-greenland' },
    { code: 'GD', name: 'Grenada', dialCode: '+1473', placeholder: '403 1234', flag: 'emojione-flag-for-grenada' },
    { code: 'GP', name: 'Guadeloupe', dialCode: '+590', placeholder: '690 12 34 56', flag: 'emojione-flag-for-guadeloupe' },
    { code: 'GU', name: 'Guam', dialCode: '+1671', placeholder: '300 1234', flag: 'emojione-flag-for-guam' },
    { code: 'GT', name: 'Guatemala', dialCode: '+502', placeholder: '5123 4567', flag: 'emojione-flag-for-guatemala' },
    { code: 'GN', name: 'Guinea', dialCode: '+224', placeholder: '601 12 34 56', flag: 'emojione-flag-for-guinea' },
    { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', placeholder: '955 012 345', flag: 'emojione-flag-for-guinea-bissau' },
    { code: 'GY', name: 'Guyana', dialCode: '+592', placeholder: '609 1234', flag: 'emojione-flag-for-guyana' },
    { code: 'HT', name: 'Haiti', dialCode: '+509', placeholder: '34 10 1234', flag: 'emojione-flag-for-haiti' },
    { code: 'HN', name: 'Honduras', dialCode: '+504', placeholder: '9123 4567', flag: 'emojione-flag-for-honduras' },
    { code: 'HK', name: 'Hong Kong', dialCode: '+852', placeholder: '5123 4567', flag: 'emojione-flag-for-hong-kong-sar-china' },
    { code: 'HU', name: 'Hungary', dialCode: '+36', placeholder: '20 123 4567', flag: 'emojione-flag-for-hungary' },
    { code: 'IS', name: 'Iceland', dialCode: '+354', placeholder: '611 1234', flag: 'emojione-flag-for-iceland' },
    { code: 'IN', name: 'India', dialCode: '+91', placeholder: '99999 12345', flag: 'emojione-flag-for-india' },
    { code: 'ID', name: 'Indonesia', dialCode: '+62', placeholder: '812 345 678', flag: 'emojione-flag-for-indonesia' },
    { code: 'IR', name: 'Iran', dialCode: '+98', placeholder: '912 345 6789', flag: 'emojione-flag-for-iran' },
    { code: 'IQ', name: 'Iraq', dialCode: '+964', placeholder: '791 234 5678', flag: 'emojione-flag-for-iraq' },
    { code: 'IE', name: 'Ireland', dialCode: '+353', placeholder: '85 012 3456', flag: 'emojione-flag-for-ireland' },
    { code: 'IT', name: 'Italy', dialCode: '+39', placeholder: '312 345 6789', flag: 'emojione-flag-for-italy' },
    { code: 'JM', name: 'Jamaica', dialCode: '+1876', placeholder: '210 1234', flag: 'emojione-flag-for-jamaica' },
    { code: 'JP', name: 'Japan', dialCode: '+81', placeholder: '90 1234 5678', flag: 'emojione-flag-for-japan' },
    { code: 'JO', name: 'Jordan', dialCode: '+962', placeholder: '7 9012 3456', flag: 'emojione-flag-for-jordan' },
    { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', placeholder: '771 123 4567', flag: 'emojione-flag-for-kazakhstan' },
    { code: 'KE', name: 'Kenya', dialCode: '+254', placeholder: '712 123456', flag: 'emojione-flag-for-kenya' },
    { code: 'KI', name: 'Kiribati', dialCode: '+686', placeholder: '72012345', flag: 'emojione-flag-for-kiribati' },
    { code: 'KW', name: 'Kuwait', dialCode: '+965', placeholder: '500 12345', flag: 'emojione-flag-for-kuwait' },
    { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', placeholder: '700 123 456', flag: 'emojione-flag-for-kyrgyzstan' },
    { code: 'LA', name: 'Laos', dialCode: '+856', placeholder: '20 23 123 456', flag: 'emojione-flag-for-laos' },
    { code: 'LV', name: 'Latvia', dialCode: '+371', placeholder: '21 123 456', flag: 'emojione-flag-for-latvia' },
    { code: 'LB', name: 'Lebanon', dialCode: '+961', placeholder: '71 123 456', flag: 'emojione-flag-for-lebanon' },
    { code: 'LS', name: 'Lesotho', dialCode: '+266', placeholder: '5012 3456', flag: 'emojione-flag-for-lesotho' },
    { code: 'LR', name: 'Liberia', dialCode: '+231', placeholder: '77 012 3456', flag: 'emojione-flag-for-liberia' },
    { code: 'LY', name: 'Libya', dialCode: '+218', placeholder: '91 2345678', flag: 'emojione-flag-for-libya' },
    { code: 'LI', name: 'Liechtenstein', dialCode: '+423', placeholder: '660 234 567', flag: 'emojione-flag-for-liechtenstein' },
    { code: 'LT', name: 'Lithuania', dialCode: '+370', placeholder: '612 34567', flag: 'emojione-flag-for-lithuania' },
    { code: 'LU', name: 'Luxembourg', dialCode: '+352', placeholder: '628 123 456', flag: 'emojione-flag-for-luxembourg' },
    { code: 'MO', name: 'Macau', dialCode: '+853', placeholder: '6612 3456', flag: 'emojione-flag-for-macau-sar-china' },
    { code: 'MK', name: 'Macedonia', dialCode: '+389', placeholder: '72 123 456', flag: 'emojione-flag-for-macedonia' },
    { code: 'MG', name: 'Madagascar', dialCode: '+261', placeholder: '32 12 345 67', flag: 'emojione-flag-for-madagascar' },
    { code: 'MW', name: 'Malawi', dialCode: '+265', placeholder: '991 23 45 67', flag: 'emojione-flag-for-malawi' },
    { code: 'MY', name: 'Malaysia', dialCode: '+60', placeholder: '12 345 6789', flag: 'emojione-flag-for-malaysia' },
    { code: 'MV', name: 'Maldives', dialCode: '+960', placeholder: '771 2345', flag: 'emojione-flag-for-maldives' },
    { code: 'ML', name: 'Mali', dialCode: '+223', placeholder: '65 01 23 45', flag: 'emojione-flag-for-mali' },
    { code: 'MT', name: 'Malta', dialCode: '+356', placeholder: '9696 1234', flag: 'emojione-flag-for-malta' },
    { code: 'MH', name: 'Marshall Islands', dialCode: '+692', placeholder: '235 1234', flag: 'emojione-flag-for-marshall-islands' },
    { code: 'MQ', name: 'Martinique', dialCode: '+596', placeholder: '696 20 12 34', flag: 'emojione-flag-for-martinique' },
    { code: 'MR', name: 'Mauritania', dialCode: '+222', placeholder: '22 12 34 56', flag: 'emojione-flag-for-mauritania' },
    { code: 'MU', name: 'Mauritius', dialCode: '+230', placeholder: '5251 2345', flag: 'emojione-flag-for-mauritius' },
    { code: 'YT', name: 'Mayotte', dialCode: '+262', placeholder: '639 12 34 56', flag: 'emojione-flag-for-mayotte' },
    { code: 'MX', name: 'Mexico', dialCode: '+52', placeholder: '1 222 123 4567', flag: 'emojione-flag-for-mexico' },
    { code: 'FM', name: 'Micronesia', dialCode: '+691', placeholder: '350 1234', flag: 'emojione-flag-for-micronesia' },
    { code: 'MD', name: 'Moldova', dialCode: '+373', placeholder: '621 12 345', flag: 'emojione-flag-for-moldova' },
    { code: 'MC', name: 'Monaco', dialCode: '+377', placeholder: '6 12 34 56 78', flag: 'emojione-flag-for-monaco' },
    { code: 'MN', name: 'Mongolia', dialCode: '+976', placeholder: '8812 3456', flag: 'emojione-flag-for-mongolia' },
    { code: 'ME', name: 'Montenegro', dialCode: '+382', placeholder: '67 622 901', flag: 'emojione-flag-for-montenegro' },
    { code: 'MS', name: 'Montserrat', dialCode: '+1664', placeholder: '492 3456', flag: 'emojione-flag-for-montserrat' },
    { code: 'MA', name: 'Morocco', dialCode: '+212', placeholder: '61 23 45 678', flag: 'emojione-flag-for-morocco' },
    { code: 'MZ', name: 'Mozambique', dialCode: '+258', placeholder: '82 123 4567', flag: 'emojione-flag-for-mozambique' },
    { code: 'MM', name: 'Myanmar', dialCode: '+95', placeholder: '9 420 123 456', flag: 'emojione-flag-for-myanmar' },
    { code: 'NA', name: 'Namibia', dialCode: '+264', placeholder: '81 123 4567', flag: 'emojione-flag-for-namibia' },
    { code: 'NR', name: 'Nauru', dialCode: '+674', placeholder: '555 1234', flag: 'emojione-flag-for-nauru' },
    { code: 'NP', name: 'Nepal', dialCode: '+977', placeholder: '984 1234567', flag: 'emojione-flag-for-nepal' },
    { code: 'NL', name: 'Netherlands', dialCode: '+31', placeholder: '6 12345678', flag: 'emojione-flag-for-netherlands' },
    { code: 'NC', name: 'New Caledonia', dialCode: '+687', placeholder: '75 12 34', flag: 'emojione-flag-for-new-caledonia' },
    { code: 'NZ', name: 'New Zealand', dialCode: '+64', placeholder: '21 123 4567', flag: 'emojione-flag-for-new-zealand' },
    { code: 'NI', name: 'Nicaragua', dialCode: '+505', placeholder: '8123 4567', flag: 'emojione-flag-for-nicaragua' },
    { code: 'NE', name: 'Niger', dialCode: '+227', placeholder: '93 12 34 56', flag: 'emojione-flag-for-niger' },
    { code: 'NG', name: 'Nigeria', dialCode: '+234', placeholder: '802 123 4567', flag: 'emojione-flag-for-nigeria' },
    { code: 'NU', name: 'Niue', dialCode: '+683', placeholder: '1234', flag: 'emojione-flag-for-niue' },
    { code: 'NF', name: 'Norfolk Island', dialCode: '+672', placeholder: '3 81 234', flag: 'emojione-flag-for-norfolk-island' },
    { code: 'KP', name: 'North Korea', dialCode: '+850', placeholder: '191 123 4567', flag: 'emojione-flag-for-north-korea' },
    { code: 'MP', name: 'Northern Mariana Islands', dialCode: '+1670', placeholder: '234 5678', flag: 'emojione-flag-for-northern-mariana-islands' },
    { code: 'NO', name: 'Norway', dialCode: '+47', placeholder: '406 12 345', flag: 'emojione-flag-for-norway' },
    { code: 'OM', name: 'Oman', dialCode: '+968', placeholder: '9212 3456', flag: 'emojione-flag-for-oman' },
    { code: 'PK', name: 'Pakistan', dialCode: '+92', placeholder: '301 2345678', flag: 'emojione-flag-for-pakistan' },
    { code: 'PW', name: 'Palau', dialCode: '+680', placeholder: '620 1234', flag: 'emojione-flag-for-palau' },
    { code: 'PS', name: 'Palestine', dialCode: '+970', placeholder: '599 123 456', flag: 'emojione-flag-for-palestinian-territories' },
    { code: 'PA', name: 'Panama', dialCode: '+507', placeholder: '6123 4567', flag: 'emojione-flag-for-panama' },
    { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', placeholder: '7012 3456', flag: 'emojione-flag-for-papua-new-guinea' },
    { code: 'PY', name: 'Paraguay', dialCode: '+595', placeholder: '961 456789', flag: 'emojione-flag-for-paraguay' },
    { code: 'PE', name: 'Peru', dialCode: '+51', placeholder: '912 345 678', flag: 'emojione-flag-for-peru' },
    { code: 'PH', name: 'Philippines', dialCode: '+63', placeholder: '905 123 4567', flag: 'emojione-flag-for-philippines' },
    { code: 'PL', name: 'Poland', dialCode: '+48', placeholder: '512 345 678', flag: 'emojione-flag-for-poland' },
    { code: 'PT', name: 'Portugal', dialCode: '+351', placeholder: '912 345 678', flag: 'emojione-flag-for-portugal' },
    { code: 'PR', name: 'Puerto Rico', dialCode: '+1', placeholder: '787 234 5678', flag: 'emojione-flag-for-puerto-rico' },
    { code: 'QA', name: 'Qatar', dialCode: '+974', placeholder: '3312 3456', flag: 'emojione-flag-for-qatar' },
    { code: 'RE', name: 'Réunion', dialCode: '+262', placeholder: '692 12 34 56', flag: 'emojione-flag-for-reunion' },
    { code: 'RO', name: 'Romania', dialCode: '+40', placeholder: '712 034 567', flag: 'emojione-flag-for-romania' },
    { code: 'RU', name: 'Russia', dialCode: '+7', placeholder: '912 345 67 89', flag: 'emojione-flag-for-russia' },
    { code: 'RW', name: 'Rwanda', dialCode: '+250', placeholder: '720 123 456', flag: 'emojione-flag-for-rwanda' },
    { code: 'BL', name: 'Saint Barthélemy', dialCode: '+590', placeholder: '690 12 34 56', flag: 'emojione-flag-for-st-barthelemy' },
    { code: 'SH', name: 'Saint Helena', dialCode: '+290', placeholder: '51234', flag: 'emojione-flag-for-st-helena' },
    { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1869', placeholder: '765 4321', flag: 'emojione-flag-for-st-kitts-and-nevis' },
    { code: 'LC', name: 'Saint Lucia', dialCode: '+1758', placeholder: '284 5678', flag: 'emojione-flag-for-st-lucia' },
    { code: 'MF', name: 'Saint Martin', dialCode: '+590', placeholder: '690 12 34 56', flag: 'emojione-flag-for-st-martin' },
    { code: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '+508', placeholder: '55 12 34', flag: 'emojione-flag-for-st-pierre-and-miquelon' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1784', placeholder: '430 1234', flag: 'emojione-flag-for-st-vincent-and-grenadines' },
    { code: 'WS', name: 'Samoa', dialCode: '+685', placeholder: '72 12345', flag: 'emojione-flag-for-samoa' },
    { code: 'SM', name: 'San Marino', dialCode: '+378', placeholder: '66 12 12 12', flag: 'emojione-flag-for-san-marino' },
    { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', placeholder: '981 2345', flag: 'emojione-flag-for-sao-tome-and-principe' },
    { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', placeholder: '512 345 678', flag: 'emojione-flag-for-saudi-arabia' },
    { code: 'SN', name: 'Senegal', dialCode: '+221', placeholder: '70 123 45 67', flag: 'emojione-flag-for-senegal' },
    { code: 'RS', name: 'Serbia', dialCode: '+381', placeholder: '60 1234567', flag: 'emojione-flag-for-serbia' },
    { code: 'SC', name: 'Seychelles', dialCode: '+248', placeholder: '2 510 123', flag: 'emojione-flag-for-seychelles' },
    { code: 'SL', name: 'Sierra Leone', dialCode: '+232', placeholder: '25 123456', flag: 'emojione-flag-for-sierra-leone' },
    { code: 'SG', name: 'Singapore', dialCode: '+65', placeholder: '8123 4567', flag: 'emojione-flag-for-singapore' },
    { code: 'SX', name: 'Sint Maarten', dialCode: '+1721', placeholder: '520 5678', flag: 'emojione-flag-for-sint-maarten' },
    { code: 'SK', name: 'Slovakia', dialCode: '+421', placeholder: '912 123 456', flag: 'emojione-flag-for-slovakia' },
    { code: 'SI', name: 'Slovenia', dialCode: '+386', placeholder: '31 234 567', flag: 'emojione-flag-for-slovenia' },
    { code: 'SB', name: 'Solomon Islands', dialCode: '+677', placeholder: '74 21234', flag: 'emojione-flag-for-solomon-islands' },
    { code: 'SO', name: 'Somalia', dialCode: '+252', placeholder: '7 1123456', flag: 'emojione-flag-for-somalia' },
    { code: 'ZA', name: 'South Africa', dialCode: '+27', placeholder: '71 123 4567', flag: 'emojione-flag-for-south-africa' },
    { code: 'KR', name: 'South Korea', dialCode: '+82', placeholder: '10 1234 5678', flag: 'emojione-flag-for-south-korea' },
    { code: 'SS', name: 'South Sudan', dialCode: '+211', placeholder: '977 123 456', flag: 'emojione-flag-for-south-sudan' },
    { code: 'ES', name: 'Spain', dialCode: '+34', placeholder: '612 34 56 78', flag: 'emojione-flag-for-spain' },
    { code: 'LK', name: 'Sri Lanka', dialCode: '+94', placeholder: '71 234 5678', flag: 'emojione-flag-for-sri-lanka' },
    { code: 'SD', name: 'Sudan', dialCode: '+249', placeholder: '91 123 1234', flag: 'emojione-flag-for-sudan' },
    { code: 'SR', name: 'Suriname', dialCode: '+597', placeholder: '741 2345', flag: 'emojione-flag-for-suriname' },
    { code: 'SZ', name: 'Swaziland', dialCode: '+268', placeholder: '7612 3456', flag: 'emojione-flag-for-swaziland' },
    { code: 'SE', name: 'Sweden', dialCode: '+46', placeholder: '70 123 45 67', flag: 'emojione-flag-for-sweden' },
    { code: 'CH', name: 'Switzerland', dialCode: '+41', placeholder: '78 123 45 67', flag: 'emojione-flag-for-switzerland' },
    { code: 'SY', name: 'Syria', dialCode: '+963', placeholder: '944 567 890', flag: 'emojione-flag-for-syria' },
    { code: 'TW', name: 'Taiwan', dialCode: '+886', placeholder: '912 345 678', flag: 'emojione-flag-for-taiwan' },
    { code: 'TJ', name: 'Tajikistan', dialCode: '+992', placeholder: '917 123 456', flag: 'emojione-flag-for-tajikistan' },
    { code: 'TZ', name: 'Tanzania', dialCode: '+255', placeholder: '621 234 567', flag: 'emojione-flag-for-tanzania' },
    { code: 'TH', name: 'Thailand', dialCode: '+66', placeholder: '81 234 5678', flag: 'emojione-flag-for-thailand' },
    { code: 'TL', name: 'Timor-Leste', dialCode: '+670', placeholder: '7721 2345', flag: 'emojione-flag-for-timor-leste' },
    { code: 'TG', name: 'Togo', dialCode: '+228', placeholder: '90 12 34 56', flag: 'emojione-flag-for-togo' },
    { code: 'TK', name: 'Tokelau', dialCode: '+690', placeholder: '5 1234', flag: 'emojione-flag-for-tokelau' },
    { code: 'TO', name: 'Tonga', dialCode: '+676', placeholder: '771 5123', flag: 'emojione-flag-for-tonga' },
    { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868', placeholder: '868 291 1234', flag: 'emojione-flag-for-trinidad-and-tobago' },
    { code: 'TN', name: 'Tunisia', dialCode: '+216', placeholder: '20 123 456', flag: 'emojione-flag-for-tunisia' },
    { code: 'TR', name: 'Turkey', dialCode: '+90', placeholder: '501 234 56 78', flag: 'emojione-flag-for-turkey' },
    { code: 'TM', name: 'Turkmenistan', dialCode: '+993', placeholder: '66 123456', flag: 'emojione-flag-for-turkmenistan' },
    { code: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1649', placeholder: '231 1234', flag: 'emojione-flag-for-turks-and-caicos-islands' },
    { code: 'TV', name: 'Tuvalu', dialCode: '+688', placeholder: '901234', flag: 'emojione-flag-for-tuvalu' },
    { code: 'UG', name: 'Uganda', dialCode: '+256', placeholder: '712 345678', flag: 'emojione-flag-for-uganda' },
    { code: 'UA', name: 'Ukraine', dialCode: '+380', placeholder: '50 123 4567', flag: 'emojione-flag-for-ukraine' },
    { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', placeholder: '50 123 4567', flag: 'emojione-flag-for-united-arab-emirates' },
    { code: 'GB', name: 'United Kingdom', dialCode: '+44', placeholder: '7911 123456', flag: 'emojione-flag-for-united-kingdom' },
    { code: 'US', name: 'United States', dialCode: '+1', placeholder: '202 555 0123', flag: 'emojione-flag-for-united-states' },
    { code: 'UY', name: 'Uruguay', dialCode: '+598', placeholder: '94 231 234', flag: 'emojione-flag-for-uruguay' },
    { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', placeholder: '91 234 56 78', flag: 'emojione-flag-for-uzbekistan' },
    { code: 'VU', name: 'Vanuatu', dialCode: '+678', placeholder: '591 2345', flag: 'emojione-flag-for-vanuatu' },
    { code: 'VA', name: 'Vatican City', dialCode: '+39', placeholder: '312 345 6789', flag: 'emojione-flag-for-vatican-city' },
    { code: 'VE', name: 'Venezuela', dialCode: '+58', placeholder: '412 1234567', flag: 'emojione-flag-for-venezuela' },
    { code: 'VN', name: 'Vietnam', dialCode: '+84', placeholder: '91 234 56 78', flag: 'emojione-flag-for-vietnam' },
    { code: 'VI', name: 'Virgin Islands, U.S.', dialCode: '+1340', placeholder: '340 642 1234', flag: 'emojione-flag-for-us-virgin-islands' },
    { code: 'WF', name: 'Wallis and Futuna', dialCode: '+681', placeholder: '50 12 34', flag: 'emojione-flag-for-wallis-and-futuna' },
    { code: 'YE', name: 'Yemen', dialCode: '+967', placeholder: '712 345 678', flag: 'emojione-flag-for-yemen' },
    { code: 'ZM', name: 'Zambia', dialCode: '+260', placeholder: '95 5123456', flag: 'emojione-flag-for-zambia' },
    { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', placeholder: '71 234 5678', flag: 'emojione-flag-for-zimbabwe' }
];


// get country by code 

export const getCountryByCode = (code) => {
    return countries.find(country => country.code === code);
}

export const getCountryByDialCode = (dialCode) => {
    return countries.find(country => country.dialCode === dialCode);
}

export const getCountryByName = (name) => {
    return countries.find(country => country.name === name);
}



