import { axiosInstance } from "@/lib/axios";
import { toast } from "react-hot-toast";

/**
 * Fetches course catalog data from the API
 * @param {Object} params - Query parameters for pagination, filtering, etc.
 * @returns {Promise<Object>} - The catalog data
 */
export const fetchCourseCatalog = async (params = {}) => {
    try {
        // This would be the actual API endpoint in production
        // const response = await axiosInstance.get('/tenant/taallum/v1/course-catalog', { params });

        // For development/mock purposes, we'll return mock data
        const response = await new Promise(resolve => {
            setTimeout(() => {
                resolve({
                    data: {
                        success: true,
                        data: MOCK_CATALOG_DATA
                    }
                });
            }, 800); // Simulate network delay
        });

        return response.data.data;
    } catch (error) {
        console.error('Error fetching course catalog:', error);
        throw error;
    }
};

/**
 * Enrolls a user in a specific course
 * @param {string|number} courseId - The ID of the course to enroll in
 * @returns {Promise<Object>} - The enrollment result
 */
export const enrollInCourse = async (courseId) => {
    try {
        // This would be the actual API endpoint in production
        // const response = await axiosInstance.post(`/tenant/taallum/v1/courses/${courseId}/enroll`);

        // For development/mock purposes, we'll simulate a successful enrollment
        const response = await new Promise(resolve => {
            setTimeout(() => {
                resolve({
                    data: {
                        success: true,
                        data: {
                            courseId,
                            enrolled: true,
                            message: "Successfully enrolled in the course"
                        }
                    }
                });
            }, 800); // Simulate network delay
        });

        // Show a success toast
        toast.success("Successfully enrolled in the course!");

        return response.data.data;
    } catch (error) {
        console.error('Error enrolling in course:', error);
        toast.error("Failed to enroll in the course. Please try again.");
        throw error;
    }
};

// Mock data that mimics the API response structure
const MOCK_CATALOG_DATA = {
    "items": [
        {
            "data": {
                "sub_items": [
                    {
                        "item_id": "8713",
                        "item_type": "learning_course_type",
                        "item_code": "DEPAGRI-FR-INDESIGN",
                        "item_name": "InDesign",
                        "item_description": "<p>&nbsp;</p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-26 16:06:20",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/ghindisgn-2020-10-26-16-08-32.jpeg",
                        "item_slug": "indesign",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "8712",
                        "item_type": "learning_course_type",
                        "item_code": "DEPAGRI-FR-ILLUSTRATEUR",
                        "item_name": "Illustrator CS6",
                        "item_description": "<p>  </p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-26 16:00:32",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/maxresdefault-2020-10-26-16-03-58.jpeg",
                        "item_slug": "illustrator-cs6",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "8711",
                        "item_type": "learning_course_type",
                        "item_code": "ENI-FR-INF-PHOTOSHOP-CC",
                        "item_name": "Photoshop CC",
                        "item_description": "<p>  </p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-26 15:55:18",
                        "is_user_enrolled": "1",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": "0",
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/OG-imaterialise-3d-design-tools-photoshop-cc-2020-10-26-15-57-25.jpeg",
                        "item_slug": "photoshop-cc",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "can_enter": true,
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "8710",
                        "item_type": "learning_course_type",
                        "item_code": "DEPAGRI-FR-INF-PHOTOSHOP-CS6",
                        "item_name": "Photoshop CS6",
                        "item_description": "<p>EW6CSPHO Photoshop CS6</p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-26 15:52:24",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/maxresdefault-2020-10-26-15-53-28.jpeg",
                        "item_slug": "photoshop-cs6",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    }
                ]
            },
            "extra_data": {
                "name": "Graphic Design Courses",
                "code": "EN-INFOGRAPHIE",
                "description": "<p>Master professional graphic design tools</p>",
                "entries_sort_attr": "item_id",
                "entries_sort_dir": "desc",
                "slug": "graphic-design-courses",
                "id": "169"
            }
        },
        {
            "data": {
                "sub_items": [
                    {
                        "item_id": "8744",
                        "item_type": "learning_course_type",
                        "item_code": "ENI-FR-ACCESS",
                        "item_name": "Access 2016",
                        "item_description": "<p>Learn database management with Access 2016</p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-28 15:05:18",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/31tmA-K3nbL-2020-10-28-15-06-18.jpeg",
                        "item_slug": "access-2016",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "8741",
                        "item_type": "learning_course_type",
                        "item_code": "ENI-FR-WINDS",
                        "item_name": "Windows 2010",
                        "item_description": "<p>Master Windows 10 operating system</p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-28 14:02:44",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/windows-10-logo-www-2020-10-28-14-03-11.jpeg",
                        "item_slug": "windows-2010",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "8739",
                        "item_type": "learning_course_type",
                        "item_code": "ENI-FR-MSLYNC",
                        "item_name": "Lync 2013",
                        "item_description": "<p> </p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-27 15:47:20",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/lynclogo-2020-10-27-15-48-20.jpeg",
                        "item_slug": "lync-2013",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "8738",
                        "item_type": "learning_course_type",
                        "item_code": "ENI-FR-MSTEAMS",
                        "item_name": "Ms Teams",
                        "item_description": "<p> </p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-27 15:44:51",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/Microsoft-teams-2020-10-27-15-45-45.jpeg",
                        "item_slug": "ms-teams",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "8736",
                        "item_type": "learning_course_type",
                        "item_code": "ENI-FR-MSPROJECT",
                        "item_name": "MS PROJECT",
                        "item_description": "<p> </p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-27 11:35:32",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/intro-msp-2022-03-22-11-39-40.jpeg",
                        "item_slug": "ms-project",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "8735",
                        "item_type": "learning_course_type",
                        "item_code": "ENI-FR-ONENOTE",
                        "item_name": "OneNote",
                        "item_description": "<p> </p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-27 11:29:04",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/microsoft-onenote-logo-2020-10-27-11-30-37.jpeg",
                        "item_slug": "onenote",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "7371",
                        "item_type": "learning_course_type",
                        "item_code": "DEMO-ENI-OUTLOOK",
                        "item_name": "Outlook 2019",
                        "item_description": "<p>Ma formation Outlook 2019</p>",
                        "item_category": "1",
                        "item_language": "french",
                        "item_create_date": "2020-06-04 17:46:54",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/bb6ae69d1c34a39acf2561b3e80c29d18baa8bf0.jpeg",
                        "item_slug": "outlook-2019",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "7370",
                        "item_type": "learning_course_type",
                        "item_code": "DEMO-ENI-PPT",
                        "item_name": "Power Point",
                        "item_description": "<p>PowerPoint : Des fondamentaux au perfectionnement</p><p><br /></p>",
                        "item_category": "1",
                        "item_language": "french",
                        "item_create_date": "2020-06-04 17:15:24",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/66b6b3e04407d9d0dc38ebea1525693b398239f6.jpeg",
                        "item_slug": "power-point",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "7368",
                        "item_type": "learning_course_type",
                        "item_code": "DEMO-ENI-EXCEL",
                        "item_name": "Excel 2019",
                        "item_description": "<p>Ma formation Excel 2019</p>",
                        "item_category": "1",
                        "item_language": "french",
                        "item_create_date": "2020-06-04 17:12:59",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/855b5434be6e5f5677a4419ad93485a0ee744b41.jpeg",
                        "item_slug": "excel-2019",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    },
                    {
                        "item_id": "6773",
                        "item_type": "learning_course_type",
                        "item_code": "DEMO-ENI-WORD",
                        "item_name": "Word 2019",
                        "item_description": "<p>Ma formation Word 2019</p>",
                        "item_category": "1",
                        "item_language": "french",
                        "item_create_date": "2020-05-06 12:15:52",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/d8fef09aa8574ae542c65a15543fbf6d20ba5a48.jpeg",
                        "item_slug": "word-2019",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    }
                ]
            },
            "extra_data": {
                "name": "Microsoft Office Courses",
                "code": "EN-MICROSOFT",
                "description": "<p>Improve your productivity with Microsoft tools</p>",
                "entries_sort_attr": "item_id",
                "entries_sort_dir": "desc",
                "slug": "microsoft-office-courses",
                "id": "170"
            }
        },
        {
            "data": {
                "sub_items": [
                    {
                        "item_id": "8740",
                        "item_type": "learning_course_type",
                        "item_code": "ENI-FR-RS",
                        "item_name": "Social Media Masterclass",
                        "item_description": "<p>Build your brand on social media platforms</p>",
                        "item_category": "1404",
                        "item_language": "french",
                        "item_create_date": "2020-10-27 15:51:58",
                        "is_user_enrolled": "0",
                        "item_visibility": "0",
                        "item_policy": "1",
                        "item_can_enroll": "2",
                        "item_type_int": "1",
                        "course_type": "elearning",
                        "duration": "0",
                        "partner_fields": null,
                        "item_price": "0",
                        "course_user_status": null,
                        "item_language_label": "French",
                        "item_language_code": "fr",
                        "item_thumbnail": "//cdn5.dcbstatic.com/files/m/u/multi_skills_docebosaas_com/assets/courselogo/original/barometre_reseaux_sociaux-2020-10-27-15-53-57.jpeg",
                        "item_slug": "social-media-masterclass",
                        "is_user_subscribed": 0,
                        "is_new": true,
                        "item_ecommerce": null,
                        "number_of_courses": null,
                        "is_affiliate": false,
                        "waiting": false,
                        "price_status": 1,
                        "is_opened": "1",
                        "item_rating": null,
                        "item_date_end": "0000-00-00 ",
                        "total_duration": null,
                        "access_status": 1,
                        "selling": false,
                        "affiliate_price": "0",
                        "quick_course_launch": false
                    }
                ]
            },
            "extra_data": {
                "name": "Digital Marketing",
                "code": "EN-DIGITAL",
                "description": "<p>Essential skills for the digital marketer</p>",
                "entries_sort_attr": "item_id",
                "entries_sort_dir": "desc",
                "slug": "digital-marketing",
                "id": "171"
            }
        }
    ],
    "extra_data": {
        "cursor": 3,
        "page_size": 10,
        "has_more_data": false
    }
};

export default {
    fetchCourseCatalog,
    enrollInCourse
};